CREATE TABLE IgracIgra 
    (
     POENI_IGRACIGRA INTEGER NOT NULL , 
     AS_IGRACIGRA INTEGER NOT NULL , 
     SK_IGRACIGRA INTEGER NOT NULL , 
     Utakmica_OZN_UTK VARCHAR (64) NOT NULL , 
     Igrac_LICBR_IGR VARCHAR (64) NOT NULL 
    )
    ON "default"
GO