CREATE TABLE Igrac 
    (
     LICBR_IGR VARCHAR (64) NOT NULL , 
     IME_IGR VARCHAR (64) NOT NULL , 
     PRZ_IGR VARCHAR (64) NOT NULL , 
     PDATUG_IGR DATE NOT NULL , 
     KDATUG_IGR DATE NOT NULL , 
     POZ_IGR VARCHAR (64) NOT NULL , 
     VIS_IGR FLOAT (3) NOT NULL , 
     SLIKA_IGR VARBINARY(MAX) , 
     Klub_ID_KLB VARCHAR (64) NOT NULL 
    )
    ON "default"
GO