ALTER TABLE IgracIgra ADD CONSTRAINT IgracIgra_PK PRIMARY KEY CLUSTERED (Utakmica_OZN_UTK, Igrac_LICBR_IGR)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON )
     ON "default" 
    GO