CREATE TABLE Klub 
    (
     ID_KLB VARCHAR (64) NOT NULL , 
     NAZ_KLB VARCHAR (64) NOT NULL , 
     DRZ_KLB VARCHAR (64) NOT NULL , 
     GRD_KLB VARCHAR (64) NOT NULL , 
     POB_KLB INTEGER NOT NULL , 
     POR_KLB INTEGER NOT NULL , 
     KOSRAZ_KLB INTEGER NOT NULL , 
     Evroliga_OZN_LIG VARCHAR (64) NOT NULL 
    )
    ON "default"
GO