CREATE TABLE Trener 
    (
     LICBR_TRN VARCHAR (64) NOT NULL , 
     IME_TRN VARCHAR (64) NOT NULL , 
     PRZ_TRN VARCHAR (64) NOT NULL , 
     PDATUG_TRN DATE NOT NULL , 
     KDATUG_TRN DATE NOT NULL , 
     Klub_ID_KLB VARCHAR (64) NOT NULL 
    )
    ON "default"
GO