CREATE TABLE Utakmica 
    (
     OZN_UTK VARCHAR (64) NOT NULL , 
     RBRKOLA_UTK INTEGER NOT NULL , 
     DOMPOENI_UTK INTEGER , 
     GOSTPOENI_UTK INTEGER , 
     KONFMDJ_UTK BIT NOT NULL , 
     Evroliga_OZN_LIG VARCHAR (64) NOT NULL , 
     Klub_ID_KLB1 VARCHAR (64) NOT NULL , 
     Klub_ID_KLB VARCHAR (64) NOT NULL 
    )
    ON "default"
GO