//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Klub : INotifyPropertyChanged
    {
        private string id;
        private string naz;
        private string drz;
        private string grad;
        private int pob;
        private int por;
        private int kosR;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klub()
        {
            this.Igracs = new HashSet<Igrac>();
            this.Rezervacijas = new HashSet<Rezervacija>();
            this.Treners = new HashSet<Trener>();
            this.Utakmicas = new HashSet<Utakmica>();
            this.Utakmicas1 = new HashSet<Utakmica>();
        }

        public string ID_KLB
        {
            get
            {
                return this.id;
            }
            set
            {
                this.id = value;
                this.RaisePropertyChanged("ID_KLB");
            }
        }
        public string NAZ_KLB
        {
            get
            {
                return this.naz;
            }
            set
            {
                this.naz = value;
                this.RaisePropertyChanged("NAZ_KLB");
            }
        }
        public string DRZ_KLB
        {
            get
            {
                return this.drz;
            }
            set
            {
                this.drz = value;
                this.RaisePropertyChanged("DRZ_KLB");
            }
        }
        public string GRD_KLB
        {
            get
            {
                return this.grad;
            }
            set
            {
                this.grad = value;
                this.RaisePropertyChanged("GRD_KLB");
            }
        }
        public string Evroliga_OZN_LIG { get; set; }
        public int POB_KLB
        {
            get
            {
                return this.pob;
            }
            set
            {
                this.pob = value;
                this.RaisePropertyChanged("POB_KLB");
            }
        }
        public int POR_KLB
        {
            get
            {
                return this.por;
            }
            set
            {
                this.por = value;
                this.RaisePropertyChanged("POR_KLB");
            }
        }
        public int KOSRAZ_KLB
        {
            get
            {
                return this.kosR;
            }
            set
            {
                this.kosR = value;
                this.RaisePropertyChanged("KOSRAZ_KLB");
            }
        }

        public virtual Evroliga Evroliga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Igrac> Igracs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacijas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trener> Treners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utakmica> Utakmicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utakmica> Utakmicas1 { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void RaisePropertyChanged(string propName)
        {
            if (this.PropertyChanged != null)
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propName));

            }
        }

        public override string ToString()
        {
            return "Name: " + this.NAZ_KLB + "\nPlace: " + this.GRD_KLB;
        }

        public override bool Equals(object obj)
        {
            if (obj == null || !(obj is Klub))
                return false;
            bool ret = ((Klub)obj).ID_KLB.Equals(this.ID_KLB);
            return ret;
        }
    }
}
