//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nalog
    {
        public string IME_NLG { get; set; }
        public string SFR_NLG { get; set; }
        public string ULOGA_NLG { get; set; }
    }
}
