//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        public string Klub_ID_KLB { get; set; }
        public string Hala_OZN_HALA { get; set; }
        public System.DateTime PVRMREZ_HALA { get; set; }
        public System.DateTime KVRMREZ_HALA { get; set; }
        public string SFR_REZ { get; set; }
    
        public virtual Hala Hala { get; set; }
        public virtual Klub Klub { get; set; }
    }
}
