//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Sudija : INotifyPropertyChanged
    {
        private string licbr;
        private string ime;
        private string prz;
        private string oznLige;
        private string drz;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sudija()
        {
            this.Sudis = new HashSet<Sudi>();
        }

        public string LICBR_SUD
        {
            get
            {
                return this.licbr;
            }
            set
            {
                this.licbr = value;
                this.RaisePropertyChanged("LICBR_SUD");
            }
        }
        public string IME_SUD
        {
            get
            {
                return this.ime;
            }
            set
            {
                this.ime = value;
                this.RaisePropertyChanged("IME_SUD");
            }
        }
        public string PRZ_SUD
        {
            get
            {
                return this.prz;
            }
            set
            {
                this.prz = value;
                this.RaisePropertyChanged("PRZ_SUD");
            }
        }
        public string Evroliga_OZN_LIG
        {
            get
            {
                return this.oznLige;
            }
            set
            {
                this.oznLige = value;
                this.RaisePropertyChanged("Evroliga_OZN_LIG");
            }
        }
        public string DRZ_SUD
        {
            get
            {
                return this.drz;
            }
            set
            {
                this.drz = value;
                this.RaisePropertyChanged("DRZ_SUD");
            }
        }

        public virtual Evroliga Evroliga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sudi> Sudis { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;

        private void RaisePropertyChanged(string propName)
        {
            if (this.PropertyChanged != null)
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propName));

            }
        }
    }
}
