//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class Trener : INotifyPropertyChanged
    {
        private string licbr;
        private string ime;
        private string prz;
        private string idKlb;
        private DateTime pDat;
        private DateTime kDat;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trener()
        {

        }

        public string LICBR_TRN
        {
            get
            {
                return this.licbr;
            }
            set
            {
                this.licbr = value;
                this.RaisePropertyChanged("LICBR_TRN");
            }
        }
        public string IME_TRN
        {
            get
            {
                return this.ime;
            }
            set
            {
                this.ime = value;
                this.RaisePropertyChanged("IME_TRN");
            }
        }
        public string PRZ_TRN
        {
            get
            {
                return this.prz;
            }
            set
            {
                this.prz = value;
                this.RaisePropertyChanged("PRZ_TRN");
            }
        }
        public System.DateTime PDATUG_TRN
        {
            get
            {
                return this.pDat;
            }
            set
            {
                this.pDat = value;
                this.RaisePropertyChanged("PDATUG_TRN");
            }
        }
        public System.DateTime KDATUG_TRN
        {
            get
            {
                return this.kDat;
            }
            set
            {
                this.kDat = value;
                this.RaisePropertyChanged("KDATUG_TRN");
            }
        }
        public string Klub_ID_KLB
        {
            get
            {
                return this.idKlb;
            }
            set
            {
                this.idKlb = value;
                this.RaisePropertyChanged("Klub_ID_KLB");
            }
        }

        public virtual Klub Klub { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;

        private void RaisePropertyChanged(string propName)
        {
            if (this.PropertyChanged != null)
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propName));

            }
        }
    }
}
