//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utakmica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utakmica()
        {
            this.IgracIgras = new HashSet<IgracIgra>();
            this.Sudis = new HashSet<Sudi>();
        }
    
        public string OZN_UTK { get; set; }
        public int RBRKOLA_UTK { get; set; }
        public Nullable<int> DOMPOENI_UTK { get; set; }
        public Nullable<int> GOSTPOENI_UTK { get; set; }
        public bool KONFMDJ_UTK { get; set; }
        public string Evroliga_OZN_LIG { get; set; }
        public string Klub_ID_KLB1 { get; set; }
        public string Klub_ID_KLB { get; set; }
    
        public virtual Evroliga Evroliga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IgracIgra> IgracIgras { get; set; }
        public virtual Klub Klub { get; set; }
        public virtual Klub Klub1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sudi> Sudis { get; set; }
    }
}
